spring:
  application:
    name: uploadFile
  servlet:
    multipart: max-file-size=5MB
  datasource:
    url: jdbc:mysql://localhost:3306/db_upload_file?createDatabaseIfNotExist=true
    username: root
    password: ${PASSWORD_DB}
  jpa:
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration